version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/user/appdata/remote-dev:/workspace:rw
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "5300:5300"
    environment:
      - NODE_ENV=development
      - PORT=5300
    restart: unless-stopped
    network_mode: bridge
