FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14

# Install additional dependencies if needed
# RUN apt-get update && apt-get install -y <package-name>

# Set the default user
USER vscode
